export const styles = {
  app: {
    fontFamily: 'system-ui, -apple-system, Segoe UI, sans-serif',
    color: '#1f2933',
    background: '#f5f7fa',
    minHeight: '100vh',
  },
  header: {
    padding: '16px 24px 8px',
    display: 'flex',
    alignItems: 'baseline',
    gap: 16,
  },
  title: { margin: 0, fontSize: 22 },
  subtitle: { margin: 0, fontSize: 13, color: '#52606d' },
  main: {
    display: 'grid',
    gridTemplateColumns: 'minmax(280px, 420px) minmax(360px, 1fr)',
    gap: 16,
    padding: '12px 24px 24px',
  },
  panel: {
    background: '#fff',
    borderRadius: 10,
    border: '1px solid #e4e7eb',
    padding: 16,
    minHeight: 520,
    display: 'flex',
    flexDirection: 'column' as const,
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  panelTitle: {
    margin: 0,
    fontSize: 13,
    textTransform: 'uppercase' as const,
    letterSpacing: 1,
    color: '#52606d',
  },
  editor: {
    width: '100%',
    maxWidth: 420,
    flex: 1,
    border: '1px solid #cbd2d9',
    borderRadius: 8,
    padding: 12,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, monospace',
    fontSize: 12.5,
    lineHeight: 1.6,
    background: '#f8f9fa',
    color: '#102a43',
    boxSizing: 'border-box' as const,
  },
  actions: { display: 'flex', gap: 8, marginTop: 10 },
  button: {
    border: '1px solid #1f2933',
    background: '#1f2933',
    color: '#fff',
    padding: '6px 12px',
    borderRadius: 6,
    fontSize: 12,
    cursor: 'pointer',
  },
  buttonSecondary: {
    border: '1px solid #1f2933',
    background: '#e4e7eb',
    color: '#1f2933',
    padding: '6px 12px',
    borderRadius: 6,
    fontSize: 12,
    cursor: 'pointer',
  },
  buttonGhost: {
    border: '1px solid #cbd2d9',
    background: '#fff',
    color: '#1f2933',
    padding: '6px 12px',
    borderRadius: 6,
    fontSize: 12,
    cursor: 'pointer',
  },
  viewport: {
    flex: 1,
    border: '1px dashed #cbd2d9',
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#fdfdfc',
    padding: 8,
  },
  tabs: { display: 'flex', gap: 8 },
  tabButton: {
    border: '1px solid #cbd2d9',
    background: '#f8f9fa',
    color: '#1f2933',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 12,
    cursor: 'pointer',
  },
  tabButtonActive: {
    border: '1px solid #1f2933',
    background: '#1f2933',
    color: '#fff',
  },
  source: {
    width: '100%',
    height: '100%',
    padding: 12,
    borderRadius: 8,
    background: '#0b1215',
    color: '#e5e7eb',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, monospace',
    fontSize: 12,
    overflow: 'auto' as const,
    whiteSpace: 'pre' as const,
  },
  errorPanel: {
    marginTop: 10,
    padding: 10,
    borderRadius: 8,
    border: '1px solid #fecaca',
    background: '#fff5f5',
    color: '#7f1d1d',
    fontSize: 12,
    whiteSpace: 'pre-wrap' as const,
  },
  errorBadge: {
    display: 'inline-block',
    padding: '1px 6px',
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    marginRight: 6,
  },
  diagnostics: {
    marginTop: 12,
    padding: 12,
    borderRadius: 10,
    border: '1px solid #e4e7eb',
    background: '#f8fafc',
    fontSize: 12,
    color: '#334e68',
  },
  diagTitle: {
    margin: '0 0 8px',
    fontSize: 12,
    color: '#52606d',
    textTransform: 'uppercase' as const,
    letterSpacing: 1,
  },
  diagRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 8,
    padding: '2px 0',
  },
};

export const errorKindColors: Record<string, string> = {
  syntax: '#dc2626',
  eval: '#ea580c',
  constraint: '#d97706',
  geometry: '#7c3aed',
  variable: '#0891b2',
  render: '#be185d',
};
